[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; font-src 'self' https://fonts.gstatic.com; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'"

[[headers]]
  for = "/sw.js"
    [headers.values]
      Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
    [headers.values]
      Cache-Control = "no-cache"

[[headers]]
  for = "/sitemap.xml"
    [headers.values]
      Cache-Control = "public, max-age=0"
